// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	articles "NEWSAPP/features/Articles"

	mock "github.com/stretchr/testify/mock"
)

// DataArtikelInterface is an autogenerated mock type for the DataArtikelInterface type
type DataArtikelInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *DataArtikelInterface) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *DataArtikelInterface) GetAll() ([]articles.Artikel, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []articles.Artikel
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]articles.Artikel, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []articles.Artikel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]articles.Artikel)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: artikel
func (_m *DataArtikelInterface) Insert(artikel articles.Artikel) error {
	ret := _m.Called(artikel)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(articles.Artikel) error); ok {
		r0 = rf(artikel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectById provides a mock function with given fields: id
func (_m *DataArtikelInterface) SelectById(id uint) (*articles.Artikel, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for SelectById")
	}

	var r0 *articles.Artikel
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*articles.Artikel, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *articles.Artikel); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*articles.Artikel)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, artikel
func (_m *DataArtikelInterface) Update(id uint, artikel articles.Artikel) error {
	ret := _m.Called(id, artikel)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, articles.Artikel) error); ok {
		r0 = rf(id, artikel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDataArtikelInterface creates a new instance of DataArtikelInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataArtikelInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataArtikelInterface {
	mock := &DataArtikelInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
